site:
  title: 스프링 배치 책 데모 버전
  start_page: demo::index.adoc
content:
  sources:
  - url: https://github.com/wikibook/springbatch.git
    branches: [0.0.1]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: partials/header-content.hbs
      contents: ./partials/header-content.hbs
    - path: partials/toolbar.hbs
      contents: ./partials/toolbar.hbs
    - path: partials/nav.hbs
      contents: ./partials/nav.hbs
  output_dir: /demo
git:
  credentials:
    contents: https://$GITHUB_TOKEN:@github.com
